### ISSUE TITLE
English Audio is not working it's playing Japanese 

### ISSUE THREAD

**Issue by Varun23102002** [xtero/CrunchyREroll#12]
I tried to change language to English but it's still play in original track

**Comment by xtero** [comment]
Can you provide me an episode link with which you have the issue ?

**Comment by Varun23102002** [comment]
Dragon Ball super episode 1 in English audio

**Comment by xtero** [comment]
Ah, it's not availlable in my region :sob:
But I think I may have already fixed it in one of the last commits.
So, it should be available soon in a release.

**Comment by Varun23102002** [comment]
No issue bro I got it new crunchyroll addon and it's working in my regional
language Hindi Dubbed too.

**Comment by xtero** [comment]
Should be fixed in version 1.0.2
