### ISSUE TITLE
Audio options

### ISSUE THREAD

**Issue by Misioslav** [xtero/CrunchyREroll#3]
Hey!
Firstly, thanks for bringing and working on the plugin.

I wonder if it would be possible to have Audio language select option.
I’ve noticed that in most anime the plugin plays Japanese audio but in some cases will use English dub (or another). I’m not a big fan of the dubs tbh and I would like to change the audio language but I can’t.

example: Shangri-la frontier it has Japanese audio on the website but only English one is being played by the plugin and I can’t change it.

**Comment by xtero** [comment]
Hello @Misioslav , It's  abug in my code.
it's already fixed on the upcoming version (I expect to release it soon)

**Comment by xtero** [comment]
Should be fixed in version 1.0.1

**Comment by Misioslav** [comment]
Seems to work now but now subs although seem to be present are not being shown (on the same anime). There is a list of subs but picking English does nothing.  On another anime apothecary dairies everything worked like a charm.

**Comment by xtero** [comment]
Can you provide me the link of the episode that is having issues ?

**Comment by Misioslav** [comment]
> Can you provide me the link of the episode that is having issues ?

Initially, it didn't work for me on this episode https://www.crunchyroll.com/watch/G14U492VG/what-do-you-play-games-for and weird sub-names were shown like below

![IMG_8882](https://github.com/xtero/CrunchyREroll/assets/46351329/0412358f-9095-44bd-8d22-ecd1aabb5fda)

but now Ive checked and on episode 9 the subs were visible normally. So there may have been some delay on the first episode.

#FunFact tho is that while trying to get to the Shangri-la via the Crunchyreroll plugin I got the following error

![IMG_8881](https://github.com/xtero/CrunchyREroll/assets/46351329/a2e1c4b0-87ce-4994-a120-51444129e296)

which corresponds to https://github.com/xtero/CrunchyREroll/issues/9

But I've managed to go around it by going to the watchlist and playing the episode directly.

**Comment by xtero** [comment]
I just release a 1.0.2 version.
It should fix most of the known issues.
